# Generated by Django 5.0.7 on 2024-07-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_cat_category_content_category_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
    ]
